# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

#comment
comments: true

# Setup
title:            ChenWenhong's Blog
tagline:          'iOS Development, Machine Learning, Algorithm'
description:      'I am a MSC student who study Advanced Computer Science at Cardiff University. In the past, I developed 4 universal iOS applications which can be downloaded on app store. Most of my experience is with Objective-C, Python and Swift. I enjoy learning Machine Learning and algorithm for leisure. Although I am still a beginner in these areas, I have strong and contiuous learning capability and adaptility.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/ChenWenhong
